name: Workflow VERCEL deploy

on: 
  push:
    branches:
      - main

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias...
        run: npm install

      - name: Compilar proyecto...
        run: npm run build
      - name: Instalar vercel...
        run: npm install -g vercel

      - name: Deploy to vercel...
        run: vercel deploy --prod --name front-vercel-rangulo --token=${{ secrets.VERCEL_TOKEN }} --yes

      - name: Conectandome a aws...
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Validar conexion aws...
        run: | 
          DATE=$(date +"%Y/%m/%d:%HH/%mm/%ss")
          aws s3 ls
      
      - name: Sync carpeta front en bucket..
        run: aws s3 sync build/ s3://bucket-codigo-backup/rangulo/vercel/codigo/version1/$DATE/ --delete

      # - name: Instalar vercel...
      #   run: npm install -g vercel

      # - name: Deploy to vercel...
      #   run: vercel deploy --prod --name front-vercel-rangulo --token=${{ secrets.VERCEL_TOKEN }} --yes