name: Workflow AWS deploy

on: 
  push:
    branches:
      - main

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias...
        run: npm install

      - name: Compilar proyecto...
        run: npm run build
      
      - name: Conectandome a aws...
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Validar conexion aws....!
        run: | 
          DATE=$(date +"%Y_%m_%d_%HH_%MM_%ss")
          echo "$DATE"
          aws s3 ls
      
      # - name: Sync carpeta front en bucket..
      #   run: aws s3 sync build/ s3://bucket-codigo-rangulo/ --delete
      
      - name: Sync carpeta front en bucket..
        run: |
          DATE=$(date +"%Y_%m_%d_%HH_%MM_%ss")
          aws s3 sync build/ s3://bucket-codigo-backup/rangulo/github_actions/codigo/version1/$DATE/ --delete

      - name: Sync carpeta front en bucket..
        run: aws s3 sync build/ s3://bucket-codigo-rangulo/ --delete

#      - name: Instalar vercel...
#        run: npm install -g vercel
#
#      - name: Deploy to vercel...
#        run: vercel deploy --prod --name front-vercel-rangulo --token=${{ secrets.VERCEL_TOKEN }} --yes